<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Code_challenge.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# NumPy and Pandas for Data Analysis
© ExploreAI Academy

In this notebook, we will cover how to use NumPy and Pandas for Data Analysis.

## Learning Objectives

* Know how to use Pandas for data analysis
* Know how to use NumPy for data analysis

## NumPy
NumPy is a Python library that supports numerical computing. It is an open source project created by Travis Oliphant in 2005. It makes working with multi-dimensional arrays easy.

It was created due to the unique challenges posed by numerical computations, such as those encountered in fields like data science, machine learning, physics, and engineering.

Since NumPy arrays are implemented in C, they are optimized for performance, providing faster execution of mathematical operations compared to Python lists. And unlike Python lists, NumPy arrays only tolerate homogeneous data types, which are stored in a contiguous block of memory, leading to efficient storage and access.

### Creating NumPy Array
A NumPy array can consist of one or more dimensions, and it can be created from a Python list. It can also be synthesized from scratch using functions like np.random.random, np.zeros, etc.

In [1]:
# Import NumPy
import numpy as np

**1D NumPy array**

In [2]:
# Create a 1D NumPy array (vector)
num_array_1 = np.array([1, 2, 3])

num_array_1

array([1, 2, 3])

In [3]:
# Dimension
num_array_1.shape

(3,)

**2D NumPy array**

In [4]:
# Create a 2D array (matrix)
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
num_array_2 = np.array(list_of_lists)
num_array_2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Dimension
num_array_2.shape

(3, 3)

**3D NumPy array**

In [6]:
# Create a 3D array (Tensor)
list_of_lists_of_lists = [list_of_lists, list_of_lists]
num_array_3 = np.array(list_of_lists_of_lists)
num_array_3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
# Dimesion
num_array_3.shape

(2, 3, 3)

**Reshaping arrays**

In [85]:
# Reshape 1D array
len_array_1 = len(num_array_1)
num_array_reshape = num_array_1.reshape(1, len_array_1)

num_array_reshape

array([[1, 2, 3]])

In [86]:
# Dimension
num_array_reshape.shape

(1, 3)

In [87]:
# Flatten the array
num_array_flat = num_array_2.flatten()
num_array_flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### NumPy Array Indexing
Similar to Python lists, NumPy employs zero-based indexing, where counting begins from zero, and the last index is excluded in the returned values, defining a range of values.

For a 2D array:

* `np.array[vertical index , horizontal index]` or `np.array[vertical index][horizontal index]` – for one element
* `np.array[vertical start:vertical end , horizontal start:horizontal end]` – for more than one element 

In [8]:
# View num_array_2
num_array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Select an element
num_array_2[1, 2]

6

In [90]:
num_array_2[1][2]

6

In [91]:
# Select a row
num_array_2[0]

array([1, 2, 3])

In [10]:
# Select a column
num_array_2[: , 0]

array([1, 4, 7])

In [16]:
# Select a range of values
# play around with values here to see how it works
num_array_2[1:2, 1:2]


array([[5]])

### Sorting NumPy arrays
We can sort arrays of various shapes with NumPy.

**Sort 1D array**

In [94]:
# Create array
num_array_5 = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
num_array_5

array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

In [95]:
# Sort 1D array
num_array_5.sort()
num_array_5

array([1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9])

**Sort 2D array**

In [96]:
# Sort 2D array
num_array_6 = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
num_array_6

array([[3, 1, 4],
       [1, 5, 9],
       [2, 6, 5]])

In [97]:
# Sorting along axis 0 (columns)
num_array_sorted_1 = np.sort(num_array_6, axis=0)
num_array_sorted_1

array([[1, 1, 4],
       [2, 5, 5],
       [3, 6, 9]])

In [98]:
# Sorting along axis 1 (rows)
num_array_sorted_2 = np.sort(num_array_6, axis=1)
num_array_sorted_2

array([[1, 3, 4],
       [1, 5, 9],
       [2, 5, 6]])

**Array Concatenation**

In [99]:
# Concatenate arrays
num_array_concat = np.concatenate((num_array_2, num_array_6), axis=1)
num_array_concat

array([[1, 2, 3, 3, 1, 4],
       [4, 5, 6, 1, 5, 9],
       [7, 8, 9, 2, 6, 5]])

In [100]:
# Stack vertically
num_array_vstack = np.vstack((num_array_2, num_array_2))
num_array_vstack

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
# Stack horizontally
num_array_hstack = np.hstack((num_array_2, num_array_2))
num_array_hstack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

**NumPy array elements deletion**

In [102]:
# Create array for deletion
num_array_del = np.vstack((num_array_2, num_array_2))
num_array_del

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
# Deleting a list of rows
np.delete(num_array_del, [1, 3], 0)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
# Deleting a list of columns
np.delete(num_array_del, [1, 2], 1)

array([[1],
       [4],
       [7],
       [1],
       [4],
       [7]])

### Data Aggregation (Summary Statistics)
We can calculate various summary statistics like mean, sum, max, etc. with NumPy.

In [105]:
# Views num_array_2
num_array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
# Sum all the elements of the array
np.sum(num_array_2)

45

In [107]:
# Row wise summation
np.sum(num_array_2, axis=1)

array([ 6, 15, 24])

In [108]:
# Column wise summation
np.sum(num_array_2, axis=0)

array([12, 15, 18])

### Vectorised operation
**Broadcasting**

Adding a scalar to all list elements

In [109]:
# Create list of lists
list_of_lists = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [110]:
# list_of_lists + 3

In [111]:
# Create an empty list to store the result
result = []

# Iterate through the outer list
for inner_list in list_of_lists:
    # Create an empty list for each inner list in the result
    new_inner_list = []

    # Iterate through the elements of the inner list
    for element in inner_list:
        # Add 3 to each element and append to the new_inner_list
        new_inner_list.append(element + 3)

    # Append the new_inner_list to the result
    result.append(new_inner_list)



In [112]:
# View the results
result

[[4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [113]:
num_array_8 = np.array(list_of_lists)
num_array_8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
num_array_8 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Element wise operation**

In [115]:
# Create two arrays
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([5, 4, 3, 2, 1])

# Vectorized multiplication
result_multiplication = array_a * array_b
result_multiplication


array([5, 8, 9, 8, 5])

## Pandas
Pandas is a Python library designed for efficient data analysis and manipulation. It builds on the foundations of NumPy and Matplotlib and was initially developed by Wes McKinney in 2008.
### Elements of Pandas
- A Pandas Series is a one-dimensional labeled array that can hold any data type. It is similar to a column in a spreadsheet
- A DataFrame is a two-dimensional labeled data structure in the Pandas library.

In [17]:
import pandas as pd

In [18]:
# Creating a Pandas series
data_array = np.array([10, 20, 30, 40, 50])
series_from_array = pd.Series(data_array)
series_from_array

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Loading Explore Electronics Sales Records
We will be working with a generated dataset containing sales records from Explore Electronics Store.

In [30]:
# Load the datset
explore_sales  = pd.read_csv("https://raw.githubusercontent.com/damian-vather/data/master/explore_electronics_sales.csv")

### Explore the dataset

In [31]:
# View first 5 rows
explore_sales.head()

date  customer_id    customer_name salesperson              product  \
0  2019-04-03          655      Scott Perez       Segun               Laptop   
1  2020-05-25          143  Patricia Warren     Andiswa   Bluetooth Keyboard   
2  2020-01-22           33    Deborah White       James               Tablet   
3  2023-06-29          617   Jeffrey Rogers      Buhari   Bluetooth Keyboard   
4  2020-10-14          719     Johnny Bauer     Andiswa  External Hard Drive   

   quantity  unit_price  
0         3      1000.0  
1         1       100.0  
2         2       900.0  
3         2       100.0  
4         2       120.0

In [32]:
# View first 10 rows
explore_sales.head(10)

date  customer_id    customer_name salesperson              product  \
0  2019-04-03          655      Scott Perez       Segun               Laptop   
1  2020-05-25          143  Patricia Warren     Andiswa   Bluetooth Keyboard   
2  2020-01-22           33    Deborah White       James               Tablet   
3  2023-06-29          617   Jeffrey Rogers      Buhari   Bluetooth Keyboard   
4  2020-10-14          719     Johnny Bauer     Andiswa  External Hard Drive   
5  2023-02-03          285    Lindsay Banks      Buhari           Headphones   
6  2023-10-24          160     Bobby Knight      Edmund           VR Headset   
7  2019-09-25          100    Frank Fischer      Zolile     Portable Speaker   
8  2023-09-30           45    Cameron Moody        Nolo   Bluetooth Keyboard   
9  2022-03-16          388    Monica Rivera     Oludare   Bluetooth Keyboard   

   quantity  unit_price  
0         3      1000.0  
1         1       100.0  
2         2       900.0  
3         2       100.0  
4         2       120.0  
5         4        50.0  
6         1       500.0  
7         5       230.0  
8         1       100.0  
9         3       100.0

In [33]:
# View last 5 rows
explore_sales.tail()

date  customer_id      customer_name salesperson  \
1995  2021-05-18          675       Alyssa Burns       Mbali   
1996  2022-01-05          771       Scott Wagner       Segun   
1997  2019-10-22          353   Barbara Sheppard     Oludare   
1998  2020-10-31          408  Monica Jenkins MD       James   
1999  2022-11-22            2     Danielle Olson       Segun   

               product  quantity  unit_price  
1995    Smart Home Hub         3       200.0  
1996  Desktop Computer         5      1200.0  
1997    Gaming Console         2       987.0  
1998            Laptop         2      1000.0  
1999            Tablet         4       900.0

**Shape of the dataset**

In [34]:
# View shape of the dataset
explore_sales.shape

(2000, 7)

**Metadata of the dataset**

In [35]:
explore_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           2000 non-null   object 
 1   customer_id    2000 non-null   int64  
 2   customer_name  2000 non-null   object 
 3   salesperson    2000 non-null   object 
 4   product        1988 non-null   object 
 5   quantity       2000 non-null   int64  
 6   unit_price     1988 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 109.5+ KB


**View rows with null values**

In [36]:
# View nulls
null_mask = explore_sales['product'].isna()
explore_sales[null_mask]

date  customer_id         customer_name salesperson product  \
15   2023-09-11          547        Zachary Nelson      Edmund     NaN   
17   2022-02-01          795            Tammy Park      Buhari     NaN   
25   2020-08-04          433            Sara Burns       Segun     NaN   
30   2021-08-24          109          Jackie Burns       James     NaN   
32   2021-05-04          614           Adam Harris      Zolile     NaN   
37   2020-12-17          622          Tanya Palmer       Mbali     NaN   
42   2020-11-28          725           Lisa Harris      Buhari     NaN   
60   2022-09-08           83         Dawn Hayes MD     Oludare     NaN   
80   2020-01-31          597          Leslie Brock     Andiswa     NaN   
107  2022-01-30          151  Alexandria Armstrong      Buhari     NaN   
108  2020-12-02          626         Dean Hamilton       Segun     NaN   
127  2019-10-11          818         Anthony White       Mbali     NaN   

     quantity  unit_price  
15          4         NaN  
17          1         NaN  
25          4         NaN  
30          5         NaN  
32          1         NaN  
37          5         NaN  
42          1         NaN  
60          5         NaN  
80          4         NaN  
107         2         NaN  
108         4         NaN  
127         4         NaN

In [37]:
# Drop nulls
explore_sales.dropna(inplace=True)

In [38]:
explore_sales.shape

(1988, 7)

In [42]:
# Drop customer_id
explore_sales.drop(columns="customer_id", inplace=True)

In [43]:
explore_sales

date      customer_name salesperson              product  \
0     2019-04-03        Scott Perez       Segun               Laptop   
1     2020-05-25    Patricia Warren     Andiswa   Bluetooth Keyboard   
2     2020-01-22      Deborah White       James               Tablet   
3     2023-06-29     Jeffrey Rogers      Buhari   Bluetooth Keyboard   
4     2020-10-14       Johnny Bauer     Andiswa  External Hard Drive   
...          ...                ...         ...                  ...   
1995  2021-05-18       Alyssa Burns       Mbali       Smart Home Hub   
1996  2022-01-05       Scott Wagner       Segun     Desktop Computer   
1997  2019-10-22   Barbara Sheppard     Oludare       Gaming Console   
1998  2020-10-31  Monica Jenkins MD       James               Laptop   
1999  2022-11-22     Danielle Olson       Segun               Tablet   

      quantity  unit_price  
0            3      1000.0  
1            1       100.0  
2            2       900.0  
3            2       100.0  
4            2       120.0  
...        ...         ...  
1995         3       200.0  
1996         5      1200.0  
1997         2       987.0  
1998         2      1000.0  
1999         4       900.0  

[1988 rows x 6 columns]

**Dataframe elements**

The elements of a dataframe are columns, index and values.

In [44]:
# View column names
explore_sales.columns

Index(['date', 'customer_name', 'salesperson', 'product', 'quantity',
       'unit_price'],
      dtype='object')

In [45]:
# View the index
explore_sales.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
      dtype='int64', length=1988)

In [46]:
# View the values
explore_sales.values

array([['2019-04-03', 'Scott Perez', 'Segun', 'Laptop', 3, 1000.0],
       ['2020-05-25', 'Patricia Warren', 'Andiswa', 'Bluetooth Keyboard',
        1, 100.0],
       ['2020-01-22', 'Deborah White', 'James', 'Tablet', 2, 900.0],
       ...,
       ['2019-10-22', 'Barbara Sheppard', 'Oludare', 'Gaming Console', 2,
        987.0],
       ['2020-10-31', 'Monica Jenkins MD', 'James', 'Laptop', 2, 1000.0],
       ['2022-11-22', 'Danielle Olson', 'Segun', 'Tablet', 4, 900.0]],
      dtype=object)

**Feature Engineering**

In [47]:
# Create total_price column
explore_sales['total_price'] = explore_sales['quantity'] * explore_sales['unit_price']

In [48]:
# View first 5 rows
explore_sales.head()

date    customer_name salesperson              product  quantity  \
0  2019-04-03      Scott Perez       Segun               Laptop         3   
1  2020-05-25  Patricia Warren     Andiswa   Bluetooth Keyboard         1   
2  2020-01-22    Deborah White       James               Tablet         2   
3  2023-06-29   Jeffrey Rogers      Buhari   Bluetooth Keyboard         2   
4  2020-10-14     Johnny Bauer     Andiswa  External Hard Drive         2   

   unit_price  total_price  
0      1000.0       3000.0  
1       100.0        100.0  
2       900.0       1800.0  
3       100.0        200.0  
4       120.0        240.0

Create year column

In [49]:
# Convert date column to datetime type
explore_sales['date'] = pd.to_datetime(explore_sales['date'])

In [51]:
explore_sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1988 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   date           1988 non-null   datetime64[ns]
 1   customer_name  1988 non-null   object        
 2   salesperson    1988 non-null   object        
 3   product        1988 non-null   object        
 4   quantity       1988 non-null   int64         
 5   unit_price     1988 non-null   float64       
 6   total_price    1988 non-null   float64       
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 124.2+ KB


In [52]:
# Create year column
explore_sales['year'] = explore_sales['date'].dt.year

In [53]:
explore_sales.head()

date    customer_name salesperson              product  quantity  \
0 2019-04-03      Scott Perez       Segun               Laptop         3   
1 2020-05-25  Patricia Warren     Andiswa   Bluetooth Keyboard         1   
2 2020-01-22    Deborah White       James               Tablet         2   
3 2023-06-29   Jeffrey Rogers      Buhari   Bluetooth Keyboard         2   
4 2020-10-14     Johnny Bauer     Andiswa  External Hard Drive         2   

   unit_price  total_price  year  
0      1000.0       3000.0  2019  
1       100.0        100.0  2020  
2       900.0       1800.0  2020  
3       100.0        200.0  2023  
4       120.0        240.0  2020

**Summary statistics (Aggregation)**

In [54]:
# Total sales to date
explore_sales['total_price'].sum()

3096027.0

In [55]:
# Five number summary
explore_sales.describe()

date     quantity   unit_price  total_price  \
count                           1988  1988.000000  1988.000000  1988.000000   
mean   2021-08-10 09:56:08.209255680     3.012575   520.332495  1557.357646   
min              2019-01-31 00:00:00     1.000000    50.000000    50.000000   
25%              2020-05-03 00:00:00     2.000000   200.000000   460.000000   
50%              2021-08-18 00:00:00     3.000000   430.000000  1000.000000   
75%              2022-11-07 12:00:00     4.000000   900.000000  2280.000000   
max              2024-01-28 00:00:00     5.000000  1300.000000  6500.000000   
std                              NaN     1.411129   390.918007  1484.605820   

              year  
count  1988.000000  
mean   2021.095070  
min    2019.000000  
25%    2020.000000  
50%    2021.000000  
75%    2022.000000  
max    2024.000000  
std       1.431375

**How many salespersons in the dataset?**

In [56]:
explore_sales['salesperson'].unique()

array(['Segun', 'Andiswa', 'James', 'Buhari', 'Edmund', 'Zolile', 'Nolo',
       'Oludare', 'Mbali'], dtype=object)

### Indexing

We can select columns or rows from the dataset.

In [57]:
# Selecting a column
explore_sales['customer_name']

0             Scott Perez
1         Patricia Warren
2           Deborah White
3          Jeffrey Rogers
4            Johnny Bauer
              ...        
1995         Alyssa Burns
1996         Scott Wagner
1997     Barbara Sheppard
1998    Monica Jenkins MD
1999       Danielle Olson
Name: customer_name, Length: 1988, dtype: object

In [58]:
# Selecting a column
explore_sales.customer_name

0             Scott Perez
1         Patricia Warren
2           Deborah White
3          Jeffrey Rogers
4            Johnny Bauer
              ...        
1995         Alyssa Burns
1996         Scott Wagner
1997     Barbara Sheppard
1998    Monica Jenkins MD
1999       Danielle Olson
Name: customer_name, Length: 1988, dtype: object

In [59]:
# Selecting a column
explore_sales[['customer_name']]

customer_name
0           Scott Perez
1       Patricia Warren
2         Deborah White
3        Jeffrey Rogers
4          Johnny Bauer
...                 ...
1995       Alyssa Burns
1996       Scott Wagner
1997   Barbara Sheppard
1998  Monica Jenkins MD
1999     Danielle Olson

[1988 rows x 1 columns]

In [60]:
# Selecting multiple columns
explore_sales[['customer_name', 'product', 'quantity']]

customer_name              product  quantity
0           Scott Perez               Laptop         3
1       Patricia Warren   Bluetooth Keyboard         1
2         Deborah White               Tablet         2
3        Jeffrey Rogers   Bluetooth Keyboard         2
4          Johnny Bauer  External Hard Drive         2
...                 ...                  ...       ...
1995       Alyssa Burns       Smart Home Hub         3
1996       Scott Wagner     Desktop Computer         5
1997   Barbara Sheppard       Gaming Console         2
1998  Monica Jenkins MD               Laptop         2
1999     Danielle Olson               Tablet         4

[1988 rows x 3 columns]

In [62]:
# Selecting a range of rows
explore_sales.iloc[0:10]

date    customer_name salesperson              product  quantity  \
0 2019-04-03      Scott Perez       Segun               Laptop         3   
1 2020-05-25  Patricia Warren     Andiswa   Bluetooth Keyboard         1   
2 2020-01-22    Deborah White       James               Tablet         2   
3 2023-06-29   Jeffrey Rogers      Buhari   Bluetooth Keyboard         2   
4 2020-10-14     Johnny Bauer     Andiswa  External Hard Drive         2   
5 2023-02-03    Lindsay Banks      Buhari           Headphones         4   
6 2023-10-24     Bobby Knight      Edmund           VR Headset         1   
7 2019-09-25    Frank Fischer      Zolile     Portable Speaker         5   
8 2023-09-30    Cameron Moody        Nolo   Bluetooth Keyboard         1   
9 2022-03-16    Monica Rivera     Oludare   Bluetooth Keyboard         3   

   unit_price  total_price  year  
0      1000.0       3000.0  2019  
1       100.0        100.0  2020  
2       900.0       1800.0  2020  
3       100.0        200.0  2023  
4       120.0        240.0  2020  
5        50.0        200.0  2023  
6       500.0        500.0  2023  
7       230.0       1150.0  2019  
8       100.0        100.0  2023  
9       100.0        300.0  2022

**Reset the index**

In [64]:
# Reset the index to date
explore_sales_2 = explore_sales.set_index('date')
explore_sales_2.head(3)

customer_name salesperson             product  quantity  \
date                                                                    
2019-04-03      Scott Perez       Segun              Laptop         3   
2020-05-25  Patricia Warren     Andiswa  Bluetooth Keyboard         1   
2020-01-22    Deborah White       James              Tablet         2   

            unit_price  total_price  year  
date                                       
2019-04-03      1000.0       3000.0  2019  
2020-05-25       100.0        100.0  2020  
2020-01-22       900.0       1800.0  2020

In [65]:
# Set salesperson as index
explore_sales_3 = explore_sales.set_index('salesperson')
explore_sales_3.head(3)

date    customer_name             product  quantity  \
salesperson                                                             
Segun       2019-04-03      Scott Perez              Laptop         3   
Andiswa     2020-05-25  Patricia Warren  Bluetooth Keyboard         1   
James       2020-01-22    Deborah White              Tablet         2   

             unit_price  total_price  year  
salesperson                                 
Segun            1000.0       3000.0  2019  
Andiswa           100.0        100.0  2020  
James             900.0       1800.0  2020

Get all Edmund's sales records

In [66]:
# Pull out Edmund's sales
explore_sales_3.loc['Edmund']

date         customer_name           product  quantity  \
salesperson                                                                
Edmund      2023-10-24          Bobby Knight        VR Headset         1   
Edmund      2022-09-11  Dr. Wendy Garcia DVM  Wireless Earbuds         1   
Edmund      2022-07-25           Jamie Myers  Wireless Earbuds         4   
Edmund      2019-05-20        Nicholas Glenn            Tablet         3   
Edmund      2021-02-21      Stephanie Hudson    Smart Home Hub         2   
...                ...                   ...               ...       ...   
Edmund      2022-12-13            Paul Brown             Drone         4   
Edmund      2019-04-18     Christian Sanchez        Smartphone         2   
Edmund      2020-07-19        Matthew Cooper   Fitness Tracker         5   
Edmund      2023-12-06         George Foster            Laptop         1   
Edmund      2021-03-12          Philip Fritz   Fitness Tracker         4   

             unit_price  total_price  year  
salesperson                                 
Edmund            500.0        500.0  2023  
Edmund            200.0        200.0  2022  
Edmund            200.0        800.0  2022  
Edmund            900.0       2700.0  2019  
Edmund            200.0        400.0  2021  
...                 ...          ...   ...  
Edmund           1300.0       5200.0  2022  
Edmund            760.0       1520.0  2019  
Edmund            430.0       2150.0  2020  
Edmund           1000.0       1000.0  2023  
Edmund            430.0       1720.0  2021  

[218 rows x 7 columns]

Get all James' sales records above the average sales

In [68]:
# Pull our James' sales
james_sales = explore_sales['salesperson'] == "James"
all_sales = explore_sales['total_price']
average_sales = explore_sales['total_price'].mean()

explore_sales[james_sales & (all_sales > average_sales)]

date     customer_name salesperson               product  quantity  \
29   2020-03-30      Brandon Paul       James  Robot Vacuum Cleaner         2   
33   2022-07-01      Erica Carter       James       Fitness Tracker         1   
69   2020-09-26     Janice Harris       James            Headphones         4   
72   2021-03-20        Dawn Brock       James      Desktop Computer         1   
73   2022-02-15      Bobby Knight       James      Wireless Earbuds         5   
...         ...               ...         ...                   ...       ...   
1881 2021-07-26    Wendy Roberson       James    Bluetooth Keyboard         1   
1922 2019-12-27    Yesenia Morris       James              E-reader         5   
1979 2020-05-11         Scott Lin       James              E-reader         5   
1986 2022-09-29   Jeffrey Andrews       James      Portable Speaker         5   
1994 2021-12-15  Mr. James Benton       James      Wireless Earbuds         5   

      unit_price  total_price  year  
29         250.0        500.0  2020  
33         430.0        430.0  2022  
69          50.0        200.0  2020  
72        1200.0       1200.0  2021  
73         200.0       1000.0  2022  
...          ...          ...   ...  
1881       100.0        100.0  2021  
1922       120.0        600.0  2019  
1979       120.0        600.0  2020  
1986       230.0       1150.0  2022  
1994       200.0       1000.0  2021  

[147 rows x 8 columns]

**Create a function to pull sales records**

In [69]:

def filter_sales_records(df, salesperson_name, start_date, end_date):
    """
    Filter sales records based on salesperson name and date range.

    Parameters:
    - df: DataFrame with columns 'Date', 'Salesperson', 'Total Sales'
    - salesperson_name: Name of the salesperson to filter records for
    - start_date: Start date of the desired date range
    - end_date: End date of the desired date range

    Returns:
    - DataFrame containing filtered sales records
    """
    # Filter based on salesperson name
    filtered_df = df[df['salesperson'] == salesperson_name]

    # Filter based on date range
    date_mask = (filtered_df['Date'] >= start_date) & (filtered_df['Date'] <= end_date)
    filtered_df = filtered_df[date_mask]

    return filtered_df

In [83]:
from datetime import datetime

date_format = '%Y-%m-%d'

start_date = "2019-01-01"
end_date = "2021-12-31"
filter_sales_records(explore_sales_2, "James", datetime.strptime(start_date, date_format), datetime.strptime(end_date, date_format) )

KeyError: 'Date'

**Sorting**

In [73]:
explore_sales_3.sort_values(by='date')

date        customer_name              product  quantity  \
salesperson                                                                  
Mbali       2019-01-31            Jenna Fox       Digital Camera         2   
Nolo        2019-01-31        Mandy Pearson             E-reader         5   
Oludare     2019-02-01      Kimberly Bowman  External Hard Drive         4   
Buhari      2019-02-02      Michael Jenkins      Fitness Tracker         5   
Zolile      2019-02-02          Tammy Meyer     Desktop Computer         2   
...                ...                  ...                  ...       ...   
Nolo        2024-01-25          Dean Little     Desktop Computer         3   
Nolo        2024-01-27        Kathryn Brown       Gaming Console         5   
Oludare     2024-01-27       Amber Mitchell       Smart Home Hub         4   
Nolo        2024-01-27       Holly Arellano     Desktop Computer         4   
Edmund      2024-01-28  Mr. Brandon Johnson             E-reader         4   

             unit_price  total_price  year  
salesperson                                 
Mbali             780.0       1560.0  2019  
Nolo              120.0        600.0  2019  
Oludare           120.0        480.0  2019  
Buhari            430.0       2150.0  2019  
Zolile           1200.0       2400.0  2019  
...                 ...          ...   ...  
Nolo             1200.0       3600.0  2024  
Nolo              987.0       4935.0  2024  
Oludare           200.0        800.0  2024  
Nolo             1200.0       4800.0  2024  
Edmund            120.0        480.0  2024  

[1988 rows x 7 columns]

**Group aggregations**

In [80]:
# Groupby year
groupby_year = explore_sales.groupby(['year'])
groupby_year['total_price'].mean()

year
2019    1558.844011
2020    1517.935233
2021    1612.586957
2022    1589.471649
2023    1498.416268
2024    1731.086957
Name: total_price, dtype: float64

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/EAI_Blue_Dark.png"  style="width:200px";/>
</div>